SELECT "historical_events"."id" AS "id",
  "historical_events"."historical_event_type_id" AS "historical_event_type_id",
  "historical_events"."worker" AS "worker",
  "historical_events"."duration_in_ms" AS "duration_in_ms",
  "historical_events"."is_failure" AS "is_failure",
  "historical_events"."details" AS "details",
  "historical_events"."created_at" AS "created_at",
  "historical_events"."created_at" AT TIME ZONE 'EST' AS "created_at (EST)",
  DATE_PART('hour', NOW() - NOW() AT TIME ZONE 'EST' )/24 AS Time_Convert,
  "historical_events"."hist_actor_user_id" AS "hist_actor_user_id",
  "historical_events"."hist_target_user_id" AS "hist_target_user_id",
  "historical_events"."hist_actor_site_id" AS "hist_actor_site_id",
  "historical_events"."hist_target_site_id" AS "hist_target_site_id",
  "historical_events"."hist_project_id" AS "hist_project_id",
  "historical_events"."hist_workbook_id" AS "hist_workbook_id",
  "historical_events"."hist_view_id" AS "hist_view_id",
  "historical_events"."hist_datasource_id" AS "hist_datasource_id",
  "historical_events"."hist_comment_id" AS "hist_comment_id",
  "historical_events"."hist_tag_id" AS "hist_tag_id",
  "historical_events"."hist_group_id" AS "hist_group_id",
  "historical_events"."hist_licensing_role_id" AS "hist_licensing_role_id",
  "historical_events"."hist_schedule_id" AS "hist_schedule_id",
  "historical_events"."hist_task_id" AS "hist_task_id",
  "historical_events"."hist_data_connection_id" AS "hist_data_connection_id",
  "historical_events"."hist_config_id" AS "hist_config_id",
  "historical_events"."hist_capability_id" AS "hist_capability_id",
  "historical_event_types"."type_id" AS "type_id",
  "historical_event_types"."name" AS "name",
  "historical_event_types"."action_type" AS "action_type",
  "hist_users"."id" AS "hist_users_id",
  "hist_users"."user_id" AS "user_id",
  "hist_users"."name" AS "hist_users_name",
  "hist_users"."domain_name" AS "domain_name",
  "hist_users"."email" AS "email",
  "hist_users"."system_user_id" AS "system_user_id",
  "hist_users"."system_admin_level" AS "system_admin_level",
  "hist_users"."hist_licensing_role_id" AS "hist_users_hist_licensing_role_id",
  "hist_users"."site_admin_level" AS "site_admin_level",
  "hist_users"."publisher_tristate" AS "publisher_tristate",
  "hist_datasources"."id" AS "hist_datasources_id",
  "hist_datasources"."datasource_id" AS "datasource_id",
  "hist_datasources"."name" AS "hist_datasources_name",
  "hist_datasources"."repository_url" AS "repository_url",
  "hist_datasources"."size" AS "size",
  "hist_datasources"."revision" AS "revision",
  "hist_views"."id" AS "hist_views_id",
  "hist_views"."view_id" AS "view_id",
  "hist_views"."name" AS "hist_views_name",
  "hist_views"."repository_url" AS "hist_views_repository_url",
  "hist_views"."revision" AS "hist_views_revision",
  "hist_workbooks"."id" AS "hist_workbooks_id",
  "hist_workbooks"."workbook_id" AS "workbook_id",
  "hist_workbooks"."name" AS "hist_workbooks_name",
  "hist_workbooks"."repository_url" AS "hist_workbooks_repository_url",
  "hist_workbooks"."size" AS "hist_workbooks_size",
  "hist_workbooks"."revision" AS "hist_workbooks_revision",
  "_users"."id" AS "_users_id",
  "_users"."name" AS "_users_name",
  "_users"."login_at" AS "login_at",
  "_users"."friendly_name" AS "friendly_name",
  "_users"."licensing_role_id" AS "licensing_role_id",
  "_users"."licensing_role_name" AS "licensing_role_name",
  "_users"."domain_id" AS "domain_id",
  "_users"."system_user_id" AS "_users_system_user_id",
  "_users"."domain_name" AS "_users_domain_name",
  "_users"."domain_short_name" AS "domain_short_name",
  "_users"."site_id" AS "_users_site_id",
  "hist_schedules"."id" AS "hist_schedules_id",
  "hist_schedules"."schedule_id" AS "schedule_id",
  "hist_schedules"."name" AS "hist_schedules_name",
  "hist_schedules"."schedule_type" AS "schedule_type",
  "hist_schedules"."priority" AS "hist_schedules_priority",
  "hist_schedules"."scheduled_action" AS "scheduled_action",
  "hist_schedules"."is_serial" AS "is_serial",
  "hist_schedules"."day_of_week_mask" AS "day_of_week_mask",
  "hist_schedules"."day_of_month_mask" AS "day_of_month_mask",
  "hist_schedules"."start_at_minute" AS "start_at_minute",
  "hist_schedules"."minute_interval" AS "minute_interval",
  "hist_schedules"."end_at_minute" AS "end_at_minute",
  "hist_schedules"."end_schedule_at" AS "end_schedule_at",
  "target user"."id" AS "_users1_id",
  "target user"."name" AS "_users1_name",
  "target user"."login_at" AS "_users1_login_at",
  "target user"."friendly_name" AS "_users1_friendly_name",
  "target user"."licensing_role_id" AS "_users1_licensing_role_id",
  "target user"."licensing_role_name" AS "_users1_licensing_role_name",
  "target user"."domain_id" AS "_users1_domain_id",
  "target user"."system_user_id" AS "_users1_system_user_id",
  "target user"."domain_name" AS "_users1_domain_name",
  "target user"."domain_short_name" AS "_users1_domain_short_name",
  "target user"."site_id" AS "_users1_site_id",
  "_workbooks"."id" AS "_workbooks_id",
  "_workbooks"."name" AS "_workbooks_name",
  "_workbooks"."workbook_url" AS "workbook_url",
  "_workbooks"."created_at" AS "_workbooks_created_at",
  "_workbooks"."updated_at" AS "updated_at",
  "_workbooks"."owner_id" AS "owner_id",
  "_workbooks"."project_id" AS "project_id",
  "_workbooks"."size" AS "_workbooks_size",
  "_workbooks"."view_count" AS "view_count",
  "_workbooks"."owner_name" AS "owner_name",
  "_workbooks"."project_name" AS "project_name",
  "_workbooks"."system_user_id" AS "_workbooks_system_user_id",
  "_workbooks"."site_id" AS "_workbooks_site_id",
  "Workbook Owner"."id" AS "_users1_id_1",
  "Workbook Owner"."name" AS "_users1_name_1",
  "Workbook Owner"."login_at" AS "_users1_login_at_1",
  "Workbook Owner"."friendly_name" AS "_users1_friendly_name_1",
  "Workbook Owner"."licensing_role_id" AS "_users1_licensing_role_id_1",
  "Workbook Owner"."licensing_role_name" AS "_users1_licensing_role_name_1",
  "Workbook Owner"."domain_id" AS "_users1_domain_id_1",
  "Workbook Owner"."system_user_id" AS "_users1_system_user_id_1",
  "Workbook Owner"."domain_name" AS "_users1_domain_name_1",
  "Workbook Owner"."domain_short_name" AS "_users1_domain_short_name_1",
  "Workbook Owner"."site_id" AS "_users1_site_id_1"
FROM "public"."historical_events" "historical_events"
  INNER JOIN "public"."historical_event_types" "historical_event_types" ON ("historical_events"."historical_event_type_id" = "historical_event_types"."type_id")
  LEFT JOIN "public"."hist_users" "hist_users" ON ("historical_events"."hist_actor_user_id" = "hist_users"."id")
  LEFT JOIN "public"."hist_datasources" "hist_datasources" ON ("historical_events"."hist_datasource_id" = "hist_datasources"."id")
  LEFT JOIN "public"."hist_views" "hist_views" ON ("historical_events"."hist_view_id" = "hist_views"."id")
  LEFT JOIN "public"."hist_workbooks" "hist_workbooks" ON ("historical_events"."hist_workbook_id" = "hist_workbooks"."id")
  LEFT JOIN "public"."_users" "_users" ON ("hist_users"."user_id" = "_users"."id")
  LEFT JOIN "public"."hist_schedules" "hist_schedules" ON ("historical_events"."hist_schedule_id" = "hist_schedules"."id")
  LEFT JOIN "public"."_users" "target user" ON ("historical_events"."hist_target_user_id" = "target user"."system_user_id")
  LEFT JOIN "public"."_workbooks" "_workbooks" ON (("hist_workbooks"."name" = "_workbooks"."name") AND ("hist_workbooks"."repository_url" = "_workbooks"."workbook_url"))
  LEFT JOIN "public"."_users" "Workbook Owner" ON ("_workbooks"."owner_id" = "Workbook Owner"."id")